### ISSUE TITLE
Translations in pod structure

### ISSUE THREAD

**Issue by flemse** [dockyard/ember-cli-i18n#108]
I think about structuring translations together with my components in pods.

fx.
``` app/my-component/locals/en.js ``` or ``` app/my-component/en.local.js ```

Would it be a good idea or am i missing something important?

**Comment by bcardarella** [comment]
I wouldn't do it this way as the module compiler isn't smart enough to know how to do this. For the time being I would stick with `/locales`. I'm open to hearing RFCs on this and how locales would fit within a  pod file structure.
