### ISSUE TITLE
ember-cli-i18n depricated ?

### ISSUE THREAD

**Issue by baskarsugumar** [dockyard/ember-cli-i18n#115]
Are you saying, not to user ember-cli-i18n and use ember-i18n instead ?

**Comment by bcardarella** [comment]
Yes: https://github.com/dockyard/ember-cli-i18n#deprecated

**Comment by baskarsugumar** [comment]
Is there any alternative for I18N wherein we are building ember client using ember-cli.



Regards,

Baskar S




 ---- On Fri, 17 Jul 2015 14:45:00 +0530 Brian Cardarella &lt;notifications@github.com&gt; wrote ----




Yes: https://github.com/dockyard/ember-cli-i18n#deprecated

**Comment by bcardarella** [comment]
ember-i18n 4.x supports ember-cli

**Comment by baskarsugumar** [comment]
Thank you verymuch bcardarella.
