### ISSUE TITLE
Accessing t helper in an initializer

### ISSUE THREAD

**Issue by tehmaestro** [dockyard/ember-cli-i18n#116]
Hi, how can I access the t helper in an initializer?
  I'm trying `container.lookup('utils.t')` but it does not work. Any ideas?

Thanks.

**Comment by bcardarella** [comment]
@tehmaestro as suggested in the README this library has been deprecated in favor of ember-i18n

**Comment by tehmaestro** [comment]
Ok, but I cannot update to Ember 1.12 as of right now ..

**Comment by tehmaestro** [comment]
Found a way. For anyone searching this, use `container.lookup('utils:t')` to get the t helper, but make sure you run your initializer after the `t` initializer: `after: ['bla', 'bla', 't'],`
