### ISSUE TITLE
[Feature Request] Loading Locales from AJAX/Model

### ISSUE THREAD

**Issue by zyllorion** [dockyard/ember-cli-i18n#41]
Hi,

Seems like it would be a good thing to hook the locale definitions into ember models, then allowing a switchLocale() function that just wraps a store.find(...)

This would be a step towards https://github.com/dockyard/ember-cli-i18n/issues/39 also.

Thanks

**Comment by zyllorion** [comment]
Hi all, really would appreciate an update on this as it's a major blocker.  Any instructions on where to populate an array or add a setter would work for now - just need to be able to set the locale translations manually.

I am thinking that maybe something along the lines of replacing 
utils:t.js result = get(locale, read(path));
with a getter from a statically declared array may work but you know the consequences this might have better than I!

**Comment by bcardarella** [comment]
You can now do this with #77. You can override the lookup handler and provide your own method
