### ISSUE TITLE
Translation suffix in the template

### ISSUE THREAD

**Issue by tinux** [dockyard/ember-cli-i18n#51]
Would be nice if this addon supports the translation suffix as documented on the ember-i18n project (https://github.com/jamesarosen/ember-i18n)

For example:

{{em-input property="name" labelTranslation=form.name.label }}

Using Handlebars subexpressions, like below, is not ideal because the translation string doesn't appear on the expected place

{{em-input property="name" label=(unbound t 'form.name.label') }}

**Comment by bcardarella** [comment]
Why not bind to a CP on your controller that returns the translation?

**Comment by tinux** [comment]
You mean like this?

controller:

formNameLabel: function(){
	return this.t('form.name.label');
}.property(),

template:

{{em-input property="name" label=formNameLabel }}

That is a possible workaround, but not the ember-way
