### ISSUE TITLE
Breaking change with 0.0.5 upgrade

### ISSUE THREAD

**Issue by sivakumar-kailasam** [dockyard/ember-cli-i18n#58]
If en.js contains an object like this,
```
header: {
		title: 'hello from %@',
}
```

and if we're using,
```
t('header.title' , 'home page' ) 
```
this breaks with the upgrade to 0.0.5 since the second argument is now meant to be the count for pluralization. The pluralization design doesn't seem to consider nested objects with strings having placeholders. This is a breaking change and since this repo follows semver, would it make sense to have a major version bump?

**Comment by bcardarella** [comment]
Apologies, I can get a fix out today

**Comment by sivakumar-kailasam** [comment]
@bcardarella anything I can do to help out?

**Comment by bcardarella** [comment]
@sivakumar-kailasam the fix is not as simple as I anticipated. For now just use `0.0.4`.

**Comment by bcardarella** [comment]
@sivakumar-kailasam FYI, this is the blocker: https://github.com/ember-cli/ember-cli/issues/3027

**Comment by bcardarella** [comment]
@sivakumar-kailasam can you try master? It required 1.10 and HTMLBars

**Comment by sivakumar-kailasam** [comment]
@bcardarella works great, finally I can move to 1.10 :smile: 

![carl-sagan-youre-awesome](https://cloud.githubusercontent.com/assets/604117/5822765/bde20bf8-a0fc-11e4-9135-85eeae5a3790.gif)

**Comment by bcardarella** [comment]
Sweet :)

**Comment by sivakumar-kailasam** [comment]
have you published to npm yet?

**Comment by bcardarella** [comment]
@sivakumar-kailasam not yet, as Ember 1.10 is not released. I think it is due this week. Once it is released I'll publish this version

**Comment by sivakumar-kailasam** [comment]
:+1:

**Comment by sivakumar-kailasam** [comment]
seeing how ember 1.10 is behind schedule can you do a beta/canary publish?

**Comment by sivakumar-kailasam** [comment]
@bcardarella @rwjblue can you guys publish one now that things are stable?

**Comment by rwjblue** [comment]
Yes, I made https://github.com/dockyard/ember-cli-i18n/issues/73 to remind myself to double check everything then get a version published.
