### ISSUE TITLE
Can not translate placeholders

### ISSUE THREAD

**Issue by jgauna** [dockyard/ember-cli-i18n#59]
Hello Brian,

I'm trying to use a translation inside a placeholder but can't make it work. Here's what I've:

```
{{input type="password" value=model.password placeholder="login.input.password" required="true" autocapitalize="off" autocorrect="off"}}
```

How should I pass the value to get the translation as the value for the placeholder? is it supported?

Regards.

**Comment by rwjblue** [comment]
Should work via sub expression, something like:

{{input type="password" value=model.password placeholder=(t "login.input.password") required="true" autocapitalize="off" autocorrect="off"}}=

**Comment by jgauna** [comment]
That works (the translation) but it's adding the value outside the input (not as a placeholder although as  a label above the input).

**Comment by rwjblue** [comment]
With which versions of this library and ember?

**Comment by jgauna** [comment]
Ember 1.9 / Handlebars 2.0 and latest of this one.

**Comment by rwjblue** [comment]
Gotcha. My suggestion should work with 1.10.x (via HTMLBars). Prior to 1.10 bound subexpressions did not work quite right...

**Comment by jgauna** [comment]
Is there any workaround ? Really need to use H 2.0

**Comment by kellyselden** [comment]
@jgauna Here is a sample of the workaround I am using until sub-expressions are more stable:

```javascript
import Ember from 'ember';
import enUs from 'your-app/locales/en-us';
import esEs from 'your-app/locales/es-es';

var i18n = {};

var locales = {
  'en-us': enUs,
  'es-es': esEs
};

function setCurrent(locale) {
  Ember.set(i18n, 'current', locales[locale]);
}

export function initialize(container, application) {
  application.register('utils:i18n', i18n, { instantiate: false });
  application.inject('route', 'i18n', 'utils:i18n');
  application.inject('model', 'i18n', 'utils:i18n');
  application.inject('component', 'i18n', 'utils:i18n');
  application.inject('controller', 'i18n', 'utils:i18n');

  setCurrent(application.defaultLocale);

  application.localeStream.subscribe(function(stream) {
    setCurrent(stream.value());
  });
}

export default {
  name: 'i18n-current',
  after: 't',
  initialize: initialize
};
```

**Comment by kellyselden** [comment]
Then use like `{{input placeholder=i18n.current.something.something}}` or `<input {{bind-attr placeholder=i18n.current.something.something}}>`

**Comment by jgauna** [comment]
@kellyselden excellent solution ! Thanks both of you for the help :)

**Comment by bcardarella** [comment]
I believe this is relevant https://github.com/emberjs/ember.js/issues/10247

**Comment by rwjblue** [comment]
@bcardarella - Correct, bound subexpressions are not supported in 1.9.

**Comment by bcardarella** [comment]
I'm going to close this as Ember 1.10 is released
