### ISSUE TITLE
using an object instead of a string in t helper broke in 0.0.5

### ISSUE THREAD

**Issue by kellyselden** [dockyard/ember-cli-i18n#60]
I have a locale changer component. It is bound to an object I create like this:

```javascript
var locales = {
  { key: 'locales.en-us', value: 'en-us' },
  { key: 'locales.es-es', value: 'es-es' },
  //...
};
```

Here is template code:

```javascript
{{#each locale in locales}}
  <li>
    <a href="#" {{action "localeChanged" locale.value}}>
      {{t locale.key}}
    </a>
  </li>
{{/each}}
```

In 0.0.4, `{{t locale.key}}` would work and essentially be `{{t 'locales.en-us'}}` and so on. In 0.0.5, you get `Uncaught Error: Assertion Failed: Missing translation for key "locale.key".` I had to update ember from 1.9.1 to 1.10.0-beta.4 in the process, maybe that has something to do with it.

**Comment by bcardarella** [comment]
@kellyselden can you try this on master?

**Comment by bcardarella** [comment]
I'm going to close as I suspect master fixes this. I can re-open if necessary

**Comment by kellyselden** [comment]
finally had some time to test this. back to working in master. thank you.

**Comment by bcardarella** [comment]
@kellyselden thank you for following up. Once 1.10 (this week I believe) is out we'll do a release.
