### ISSUE TITLE
Seems like its not working with ember 1.9.1 and ember-cli 1.7

### ISSUE THREAD

**Issue by leoGalani** [dockyard/ember-cli-i18n#62]
Seems like its not working with ember 1.9.1 and ember-cli 1.7

     Uncaught Error: Could not find module ember-metal/streams/utils

If i remove the package, it all work fine... ( clean project)

**Comment by bcardarella** [comment]
Correct, 0.0.5 is a bad release. You'll need to rollback to 0.0.4. 0.0.6 will be ember 1.10+

**Comment by bcardarella** [comment]
Alternatively if you use the master branch and the latest beta of Ember 1.10 you should be good too

**Comment by gnapse** [comment]
I'm trying to incorporate this gem into my project, and I installed v0.0.4, after having initially installed v0.0.5 and getting the error mentioned above. However, I'm still getting the same error on the browser's console, after downgrading to v0.0.4.

    Uncaught Error: Could not find module ember-metal/streams/stream

I'm using the following versions of stuff:

```
node       : 0.10.35
npm        : 2.1.8
Ember CLI  : 0.1.12
Ember      : 1.8.1
Ember Data : 1.0.0-beta.12
Handlebars : 1.3.0
jQuery     : 1.11.2
```

But supposedly the 0.0.4 release is ok. Any ideas why?

**Comment by bcardarella** [comment]
There are certain APIs that aren't available in Ember 1.8 that 0.0.5 is expecting. However, 0.0.5 is also broken. We are awaiting the release of Ember 1.10 before cutting 0.0.6

**Comment by kellyselden** [comment]
@gnapse maybe try handlebars 2.0.0

**Comment by bcardarella** [comment]
@kellyselden the issue is that he is using Ember 1.8 which doesn't have Stream support

**Comment by gnapse** [comment]
Ember 1.8 is what the latest ember-cli gives me out of the box. I'll dig into upgrading it, but fi you could suggest anything, let me know.

**Comment by gnapse** [comment]
Upgraded to Ember 1.10 and handlebars 2.0.0. Everything's fine now. Thanks again.

**Comment by bcardarella** [comment]
@gnapse you can use master branch of this repo as well now that you're on the 1.10
