### ISSUE TITLE
[Feature Proposal] Allow user to supply fallback value/path(s)

### ISSUE THREAD

**Issue by dlangevin** [dockyard/ember-cli-i18n#63]
I'd like to have something similar to what `I18n` rubygem allows with regard to default values and alternate lookup paths.  Basically, this allows us to supply a default string if there is no value for the key supplied and/or alternate paths, which are resolved in the specified order until we have a match or we reach the last value, which is used as the default.

My use-case is for a mixin to `DS.Model`, which will give me translatable field names, defaulting to the actual name of the field (`myModel.humanizedName('theField')`), which would search for a custom field name and default to `"The Field"` or something like that.

I'd be happy to submit a PR if you think that behavior is something that you'd like in the library.

E.g.
```js
// app/locales/en.js
{
  foo: 'bar',
  baz: {
    qux: 'corge'
  }
};

t = this.container.lookup('utils:t');

t('baz.qux'); // "corge"
t('baz.foo'); // Error!
t('baz.foo', { default: 'Fallback!' }); // 'Fallback!'
t('baz.foo', { default: ['foo', 'Fallback!'] }); // 'bar'
```

**Comment by kanongil** [comment]
A default / fallback feature would be much appreciated.

##### Use case
 I have an object retrieved from an external service which includes a `category` field. I would like to present a translation of this value, defaulting to a specific value in case it is not in the translation file.

To complicate matters, I would like the fallback to be configurable for interpolated values, and templates as well.

**Comment by bcardarella** [comment]
you can now override the handlers to provide your own customizations. Please see: https://github.com/dockyard/ember-cli-i18n#overriding-the-locale-lookup-handler
