### ISSUE TITLE
[Feature proposal] Allow subclassing of the T util

### ISSUE THREAD

**Issue by acorncom** [dockyard/ember-cli-i18n#65]
I'm working on a project that involves needing fallbacks (in some ways similar to #63, but differently).

For our system, we're needing to allow clients to optionally specify certain localized strings for fields in our system.  These strings can change depending on the route.  We wouldn't have to have async support for this, but it might be nice.

Currently, it seems like the best approach to handling this would be to refactor `addon/utils/t.js` to shift:

```
result = get(locale, read(path));
```

to this:
```js

result = this.lookupResult(locale, path);

...

this.lookupResult = function(locale, path) {
  return get(locale, read(path));
};
```

Subclasses would then be able to handle looking up results in different places.

Is this something you'd want a pull request for?  I'm happy to send in a pull request, but may need a bit of guidance on how you want the subclassing to be allowed in the system (I'm relatively new to the JS/Ember world).

My initial thoughts on how to handle the changes would be to both change the above into a method and then shift `T` to be an `Ember.Object`.  That would then seem to allow us to extend the registered `utils:t` instance through an initializer.

Thoughts?

**Comment by bcardarella** [comment]
:+1: good idea, do you want to PR?

**Comment by acorncom** [comment]
@bcardarella Yep, happy to.  Just wanted to make sure you wanted it before I bothered ;-)

**Comment by acorncom** [comment]
@bcardarella Hmm, start wondering if I'm in over my head.  Any pointers on how to get `T.create` to act as a factory in the container, but also pass it parameters so it can instantiate a subclass?  I don't see any way to pass additional attributes through the Ember container to it ...

**Comment by bcardarella** [comment]
I'm unsure what you're trying to do.

**Comment by acorncom** [comment]
You mean you can't read my mind? ;-)

Sorry, let me see if I can state it far clearer (I've been mulling over this for a bit longer now).

What I'm wanting to do (I think I have the proper terminology) is to setup a subclass of the `addon/utils/t.js` factory, which would allow me to swap in a different implementation of `this.lookupResult()` (see above).  Here's the code that seems to be causing me problems:

```javascript
T.create = function(attributes) {
  var t = new T(attributes);
  // this seems to be where I'm tripped up
  var fn = bind(t, t.t);
  fn.destroy = function() {};
  return fn;
};
```

Currently, we seem to tightly bind the creation of our T factory instance with the binding of the `t()` method.  Is there any way we can split those into separate operations so that I can swap in a subclass of the factory instance?

I'm envisioning registering the default `T` 'factory' with the `container` if there isn't already on setup and then setting up the binding of the factory `t()` method later on (to an instance of whichever factory is stored in the container).

Am I making sense?

**Comment by bcardarella** [comment]
So that crazy code allows us to export the function binding. This way we can just call `this.t(...)` from controllers, components, routes, etc... instead of exporting the object which would require us to call `this.t.t(...)` which seems odd.

Let's take another approach to this: why do you want to modify the lookup handler? What is your use-case?

**Comment by acorncom** [comment]
I'd gathered that that was what it was doing (after much head scratching ;-)

Re: use case, here goes.

We're trying to handle swapping out translation strings depending on the route selected (we'll be using different strings depending on the location in the app, even though we're using the same translation keys under the hood).  At the moment we don't **have to have** `async` loading of translations, but that will be requested pretty quickly, as our app is pretty heavily dependent on translations.

So what I was aiming for was a way to load in all our additional logic about what translation keys to use when without embedding a lot of that within the main add-on (as I don't see it being a common use case).

I'd thought I'd found a way to do it by having the locale/en.js file be an intelligent model (where we could embed logic about how to resolve the various keys), but the model gets cached in the container after initial lookup and I can't currently trigger a change there (unless I trash it as needed ...  hmm ...)

Thoughts?

**Comment by bcardarella** [comment]
I think it might make more sense to extract out the lookup handler as a service that itself can be lookup. Something similar to what happens in ember-validations where it will first attempt to find the service in the app layer, if that is a miss it will fallback to the default lookup handler.

**Comment by acorncom** [comment]
Agreed, that sounds like a good plan.  Any suggestions on how to go about that?  That was the path I started heading down, but the "crazy code" (as you put it) ended up throwing me for a bit of a loop ;-)

Ideally we'd be able to have the lookup handler be extensible by other folks as needed.

**Comment by bcardarella** [comment]
I'm currently working on a solution (started last night). It might be a day or two as it has a bunch of edge cases I'm trying to account for.

**Comment by acorncom** [comment]
Understood on the edge cases and appreciated.  I started in down that path before I opened this issue but I broke **every** test.  That's when I began realizing the complexity of your relatively simple looking code :-)

**Comment by acorncom** [comment]
@bcardarella Any further thoughts on these changes?  I know you guys have been getting hammered weather-wise, so understood if you've had a few other things you've been working on ;-)

**Comment by bcardarella** [comment]
@acacheung sorry it took longer than it should have, the PR is above. Once green I'll merge

**Comment by acorncom** [comment]
@bcardarella Sweet!  Thanks very much!
