### ISSUE TITLE
Using a test framework other than QUnit causes errors

### ISSUE THREAD

**Issue by dlangevin** [dockyard/ember-cli-i18n#67]
We automatically inject tests using QUnit syntax, so anyone using an alternate testing framework will get failures.

I have a branch that just conditionally excludes these tests if `module` is not defined.  We could also add support for different frameworks as a configuration option in `config/environment.js`  I'd be willing to work on support for Mocha, since that's the framework we are using

**Comment by rwjblue** [comment]
Yes, we should support this.

**Comment by bcardarella** [comment]
@rwjblue should the test-support assets work with ember-mocha?

**Comment by dlangevin** [comment]
I was thinking of doing multiple adapters and trying to auto detect the library that has been loaded. In addition there would be a config option to specify an adapter. The if you don't specify one and we can't auto detect it would default to a NullAdapter which (unsurprisingly) does nothing 



—

**Comment by bcardarella** [comment]
in `test-support/ember-cli-i18n-test.js` you could probably just do:

```javascript
if (window.QUnit) {
   // current QUnit tests
} else {
  // mocha tests
}
```

**Comment by dlangevin** [comment]
Any thoughts on how to unit test this?  I am trying to think of an elegant way to run (or mock out in some way) mocha tests from within QUnit
