### ISSUE TITLE
Assertion Failed: calling set on destroyed object (the app object)

### ISSUE THREAD

**Issue by gnapse** [dockyard/ember-cli-i18n#69]
I have the following observer in the session controller of my app.

```coffeescript
  onLocaleChanged: (->
    app = @container.lookup('application:main')
    currentLocale = Ember.get(app, 'locale') || app.defaultLocale
    newLocale = Ember.get(this, 'currentUser.locale') || app.defaultLocale
    if newLocale != currentLocale
      Ember.set(app, 'locale', newLocale)
  ).observes('currentUser.locale')
```

This controller has a `currentUser` property, and the user has a `locale` property. The intention is that, whenever the value of `currentUser.locale` changes (either because the current user changed, or its locale changed) to update the app locale, so that the user interface is shown in the new locale.

The problem is that on the line `Ember.set(app, 'locale', newLocale)` I sometimes get the following error:

```
Assertion Failed: calling set on destroyed object
```

I've noticed that this never happens on the first time the locale changes once the app is loaded on a browser tab. But the second time the language changes this occurs.

It appears that the app object that I'm getting is cached on the first call to this observer, and then when called on the second time, the cached app reference is no longer relevant. But this is all me guessing. I really have no idea if this is the reason, and if it is, how to solve it.

**Comment by bcardarella** [comment]
that is very strange. @rwjblue do you know what is happening here?

**Comment by rwjblue** [comment]
Is this in tests or in the real running app?  The `app` should not be destroyed when running for "realz", but if you are seeing this in a test (assuming ember-cli style acceptance tests), then your observer may be being triggered when the application is torn down (generally in `teardown`/`afterEach`).

**Comment by acatarineu** [comment]
This is happening to me too. It seems that views in the state 'destroying' get notified by the stream sometimes, and I think this is causing the assert.

**Comment by gnapse** [comment]
@rwjblue this is not in a test, this in a running app, in the browser, in development environment.

**Comment by acatarineu** [comment]
I can confirm this is happening when the stream notifies destroyed views, at least for me. If I add the obj.isDestroyed check in the following code (ember-metal/property-set.js) it is solved:

```javascript
    function connectStreamBinding(obj, key, stream) {
      var onNotify = function(stream) {
        _suspendObserver(obj, key, null, didChange, function() {
          if (!obj.isDestroyed) {
            trySet(obj, key, stream.value());
          }
        });
      };
```
Not sure if trySet should be avoiding the assertion when obj is destroyed.

**Comment by Kilowhisky** [comment]
I am also getting the same error but it appears it is happening for a different reason for me. 

Here is my code that is causing the error

````javascript
    onCurrentLanguageChanged: function(){

        // Set the app language
        var application = this.container.lookup('application:main');
        Ember.set(application,'locale', this.get('currentLanguage'));

    }.observes('currentLanguage'),
````

currentLanguage is an object property i have in a language switcher component. 

For me the language switcher breaks after i transition to another route from an action in the controller like so

````javascript
actions: {
     goToLogin: function(){
         this.transitionToRoute('blahblahblah');
     },
}
```
If i do {{link-to}} helpers it works perfectly fine. 

Just for reference i have my language switcher in my application.hbs and the action is inside a sub route.

**Comment by coleww** [comment]
I'm having the same error as @gnapse , when running the app in development the first locale change is fine, but the second locale change throws this error.

What is very weird is that the translations update correctly even when this error is thrown. 

I tried to make a dummy app to replicate this behavior, but could not seem to trigger it, so it may be related to some dependency.

**Comment by dennismende** [comment]
Are there any news concerning this topic?

**Comment by ericestes** [comment]
I've had this happen when using the {{helper parameter=(t 'my-key')}} syntax. It works at first, but if I transition to a different page and back and then change the language, I get the error.

**Comment by Kilowhisky** [comment]
The try catch works under some circumstances but not all of them.

**Comment by digitalbreed** [comment]
Joining the unhappy crowd experiencing this issue. Any news on this?

**Comment by jaimevent** [comment]
I'm experiencing the same issue. Any help appreciated.

**Comment by a6ftcruton** [comment]
+1 on this issue. Navigating back to earlier show routes was causing problems for me (e.g. going to /messages/contact/:id then navigating to /messages/athlete/:id and pressing "back" or navigating back to /messages/contact/:id via the link was throwing the "calling set on destroyed object" error. 

I found that I had an afterModel hook in each show route that was calling model.reload(). Removing these afterModel hooks cleared up the issue. This is probably specific to my setup, but maybe it will shed light on this issue for others.

**Comment by Kilowhisky** [comment]
I gave up and ditched to https://github.com/jamesarosen/ember-i18n. Its shaping up to be a very nice replacement.

**Comment by bcardarella** [comment]
@Kilowhisky this is the correct path, we have advocated for people to migrate to ember-i18n
