### ISSUE TITLE
Setting new locale has no effect

### ISSUE THREAD

**Issue by jkblgithub** [dockyard/ember-cli-i18n#72]
I check the user's language in a function called ready in app.js and then set the locale as advised in your docs:
var set = Ember.set;
var application = container.lookup('application:main');
set(application, 'locale', 'fr');

This works fine. However, when the user logs in, and I try to change the locale using the code above in my log in controller, the new locale setting does not take effect. I have logged the locale property on the application object and can confirm that it does in fact get changed when I set it in the log in controller. Is there anything else I need to do to make the locale change take effect? We are on Ember 1.9 and using v0.0.4 of ember-cli-i18n

**Comment by rwjblue** [comment]
The README is documented the master version (hopefully in a new release soon see https://github.comw/dockyard/ember-cli-i18n/issues/73). Ember 1.9 cannot be used to re-render in this scenario, this requires 1.10 or above.

**Comment by jkblgithub** [comment]
Thanks!
