### ISSUE TITLE
[Documentation] Link to a translation manager

### ISSUE THREAD

**Issue by kellyselden** [dockyard/ember-cli-i18n#74]
I wrote a translation manager for this addon, [ember-cli-i18n-csv](https://github.com/kellyselden/ember-cli-i18n-csv). It creates a csv file out of all your locale files to send out to translators.

I wrote it because I was sending out the locale js files to translators, but once they started translating, they lost context of the English reference strings, and also screwed up the js formatting and string escaping.

This puts all languages side-by-side with string handling. Then another command puts the new translations back into your locale files.

I thought anyone else doing heavy localization might want to use this, so maybe a link in the README would be help.

**Comment by sivakumar-kailasam** [comment]
@kellyselden :100: I was about to write something for the same, thankfully I watch this repo :smiley:

**Comment by bcardarella** [comment]
It would be best to put this in the wiki
