### ISSUE TITLE
Support keys with keypaths

### ISSUE THREAD

**Issue by thejameskyle** [dockyard/ember-cli-i18n#80]
A lot of i18n apis use keys with keypaths instead of nested objects (including ember-i18n). It'd be nice if they were supported here too.

```js
{
  "foo.bar.baz": "Foo Bar Baz"
}
```

**Comment by thejameskyle** [comment]
Oh just found #68 as I was looking for issues related to JSON.

**Comment by bcardarella** [comment]
Closing in favor of #68
