### ISSUE TITLE
Lazy lookup, Rails style

### ISSUE THREAD

**Issue by ZenCocoon** [dockyard/ember-cli-i18n#89]
How do you feel about adding support for lazy lookup, the same way as Rails does it?

I've already made a Broccoli filter a few month back, I think the same would be perfect built-in here.

https://github.com/BookingSync/broccoli-i18n-lazy-lookup
https://github.com/BookingSync/ember-cli-i18n-lazy-lookup

The idea of using a Broccoli filter was to also do the processing at built time, therefore this won't have any performance impact when your app is shipped.

**Comment by bcardarella** [comment]
You should be able to get what you want by overriding the lookup handler: https://github.com/dockyard/ember-cli-i18n#overriding-the-locale-lookup-handler

**Comment by ZenCocoon** [comment]
Interesting, I'll look into this solution then. Thanks @bcardarella
