### ISSUE TITLE
How to get available locales?

### ISSUE THREAD

**Issue by jelhan** [dockyard/ember-cli-i18n#99]
Is there anyway to get an array of available locales i.e. for use in a language switch?

**Comment by bcardarella** [comment]
I'm not sure how that would work. We are relying on the ember resolver to lookup the languages (by default anyway). I'm not sure if es6 modules allow for giving an array of modules under a given namespace. For example, if you had

* `ember-cli-i18n/locales/en`
* `ember-cli-i18n/locales/fr`
* `ember-cli-i18n/locales/gb`

it would be nice to get a list of all names under `ember-cli-i18n/locales`, this would get you what you want. @rwjblue is anything like this possible?

**Comment by rwjblue** [comment]
```
var availableLocales = Ember.keys(requirejs.entries).filter(function(module) {
  return module.match(/ember-cli-i18n\/locales\//)
});
```

**Comment by bcardarella** [comment]
:chicken: :boom:

**Comment by bcardarella** [comment]
@jelhan I would suggest using @rwjblue's code. I thought about this and I don't think it should be a feature in the library. My reasoning is that with the adapter that can override how locales are looked up this would present a feature that would/could break. I don't mind putting this into the Wiki as a suggestion though.

**Comment by jelhan** [comment]
@rwjblue thanks for pushing me in the right direction. There were some bugs in your code. Here is a fixed version:
```
var availableLocales = Ember.keys(requirejs.entries).filter(function(module) {
  return module.match(new RegExp(application.get('modulePrefix') + '/locales/'));
}).map(function(localesModule) {
  return localesModule.replace(application.get('modulePrefix') + '/locales/', '');
});
```

**Comment by kellyselden** [comment]
@jelhan @rwjblue @bcardarella Love the solution. I plan on using it in multiple places so I threw it in an addon [ember-cli-i18n-locales](https://github.com/kellyselden/ember-cli-i18n-locales/).
```
import getLocales from 'ember-cli-i18n-locales/utils/get-locales';

var locales = getLocales();
```

**Comment by bcardarella** [comment]
![](http://i292.photobucket.com/albums/mm31/leecothran/Borat-VeryNice.gif)
